#!/bin/sh

# Send the header so that i3bar knows we want to use JSON:
echo '{"version":1, "click_events": true }'

# Begin the endless array.
echo '['

# We send an empty first array of blocks to make the loop simpler:
echo '[],'

# Now send blocks with information forever:
conky -d -c $HOME/.config/conky/conkyi3

IFS="}"
while read;do
  IFS=" "
  STR=`echo $REPLY | sed -e s/[{}]//g -e "s/ \"/\"/g" | awk '{n=split($0,a,","); for (i=1; i<=n; i++) {m=split(a[i],b,":"); if (b[1] == "\"name\"") {NAME=b[2]} if (b[1] =="\"x\"") {X=b[2]} if (b[1] =="\"y\"") {Y=b[2]} } print NAME " " X " " Y}'`
  read NAME X Y <<< $STR
  X=$(($X-200))
  Y=$(($Y-82))
  case "${NAME}" in
    \"toggl\")
      python ~/projects/conky-toggl-button/toggl_toggl.py
      python ~/projects/conky-toggl-button/togglconky.py
      ;;
    \"toggl_descr\")
      python ~/projects/conky-toggl-button/toggl_change_name.py $X 1700
      python ~/projects/conky-toggl-button/togglconky.py
      ;;
    \"toggl_project\")
      python ~/projects/conky-toggl-button/toggl_change_project.py $X $Y
      python ~/projects/conky-toggl-button/togglconky.py
      ;;
    \"mail\")
      chromium https://inbox.google.com/u/0/ > /dev/null
      ;;
    \"chalmersmail\")
      chromium https://inbox.google.com/u/1/ > /dev/null
      ;;
    *)
      ;;
  esac
  IFS="}"
done
